export const SET_USERS = "SET_USERS";
export const SET_USER_SESSION = "SET_USER_SESSION";
export const SET_TOURNAMENTS = "SET_TOURNAMENTS";
export const SET_INSCRIPTIONS = "SET_INSCRIPTIONS";
export const SET_PARTICIPANTS = "SET_PARTICIPANTS";
export const SET_PLAYERS = "SET_PLAYERS";
export const SET_MATCHES = "SET_MATCHES";
